M48
; DRILL file {KiCad 9.0.0} date 2025-03-30T22:44:26+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-30T22:44:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X8.7106Y-3.189
T2
X0.4528Y-0.8268
X0.4528Y-3.6713
X9.252Y-0.8268
X9.252Y-3.6713
M30
